spring:
  datasource:
    url: jdbc:mysql://101.34.171.190:3306/personal_website?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 57123456


mybatis:
  type-aliases-package: lxy.personal.website.entity
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9264
